### ISSUE TITLE
仪表盘错位

### ISSUE THREAD

**Issue by qianshancun** [meathill/fasttest#13]
这个问题在iOS的chrome，safari和desktop（macos）的safari会出现，浏览器均为最新版。

只有在desktop（macos）的chrome没有问题。

具体效果如下：

![image](https://user-images.githubusercontent.com/85496448/121825510-71937b80-cce5-11eb-825d-b34e1c771d66.png)

**Comment by meathill** [comment]
Safari 不支持 SVG 的 `transform` 属性，改成样式就好了。
