### ISSUE TITLE
桌面的Safari较小幅度错位

### ISSUE THREAD

**Issue by qianshancun** [meathill/fasttest#16]
![image](https://user-images.githubusercontent.com/85496448/121977988-d28c8380-cdb9-11eb-8e93-2d6ba6a2e59e.png)

桌面的Chrome看起来暂时没出现这种问题。

**Comment by meathill** [comment]
这个是 Safari 的 bug，它无法正确的绘制 SVG 半圆，你可以分别在 Chrome 和 Safari 里打开 https://codepen.io/meathill/pen/yLMQqBQ。
