### ISSUE TITLE
在桌面端resize窗口的时候，下方的test-items错位。

### ISSUE THREAD

**Issue by qianshancun** [meathill/fasttest#17]
如下所示，chrome和safari桌面端都存在这个问题：

![temp-layout](https://user-images.githubusercontent.com/85496448/121978167-36af4780-cdba-11eb-8547-62826041e743.gif)

补充，在进入device view的时候，用responsive模式去resize，就不存在这个问题：

![tmp-responsive-resizing](https://user-images.githubusercontent.com/85496448/121989858-661c7f00-cdcf-11eb-99b6-15775120abb5.gif)

**Comment by meathill** [comment]
无法重现，macOS，Chrome/Safari/Edge/Firefox。

**Comment by meathill** [comment]
在 Windows 下可以重现，出现纵向滚动条后宽度计算有问题，只在小屏出现。我倾向于这是 Windows Chrome 的 bug。

**Comment by qianshancun** [comment]
> 无法重现，macOS，Chrome/Safari/Edge/Firefox。

奇怪，我就是macOS录屏的。但是我刚刚重新resize一下发现问题已经结局了。那先忽略吧。
