### ISSUE TITLE
请评估一下png素材更新为svg的可行性（最好是inline）

### ISSUE THREAD

**Issue by qianshancun** [meathill/fasttest#4]
希望把 `src/assets` 下的所有png素材替换为svg形式。现在在retina屏幕上看比较难看，如果替换成SVG，并且都用inline SVG的话，也省了不少http请求。

请 @meathill 看看是否有什么问题或者坑，如果没问题我就来生成所有的SVG代码了。

**Comment by meathill** [comment]
理论上当然是可行，不过我怀疑设计稿里也未必能导出 SVG，比如 Facebook 图标。

另外 inline svg 可能会破坏当前页面效果，普通 svg 也有可能。主要是因为导出的时候，它不一定会按照位图这样保持大小+裁剪空白像素。

**Comment by qianshancun** [comment]
> 理论上当然是可行，不过我怀疑设计稿里也未必能导出 SVG，比如 Facebook 图标。
> 
> 另外 inline svg 可能会破坏当前页面效果，普通 svg 也有可能。主要是因为导出的时候，它不一定会按照位图这样保持大小+裁剪空白像素。

设计稿能导出的，我来弄；Facebook的那些图标都好弄，我之前做过相关的事情。

我先导出一下看看。

**Comment by meathill** [comment]
需要设计师在设计的时候用的就矢量图。不然你会发现导出的 SVG 其实是 SVG 内嵌了一个 Base64 编码的位图。

**Comment by qianshancun** [comment]
> 需要设计师在设计的时候用的就矢量图。不然你会发现导出的 SVG 其实是 SVG 内嵌了一个 Base64 编码的位图。

嗯，好的。sketch应该是适量描述的图形（导出之后都是path、circle、rect这些svg标签），放心。这个我懂的~

**Comment by qianshancun** [comment]
都导出SVG并进行了优化，现在体积很小了。可以打开看看：

[svg_assets.zip](https://github.com/meathill/fasttest/files/6623267/svg_assets.zip)


@meathill

**Comment by meathill** [comment]
都换了，clock-bg 少了进度的背景，我导出的尺寸不太对，麻烦再处理一下

**Comment by qianshancun** [comment]
> 都换了，clock-bg 少了进度的背景，我导出的尺寸不太对，麻烦再处理一下

辛苦了~

麻烦看看 clock-empty.svg 是否是需要的素材：

[clock-empty.svg.zip](https://github.com/meathill/fasttest/files/6638576/clock-empty.svg.zip)


svg内容：

```
<svg width="354" height="354" xmlns="http://www.w3.org/2000/svg"><path d="M177 0c97.754 0 177 79.246 177 177 0 48.877-19.811 93.127-51.842 125.158l-7.071-7.071C325.307 264.866 344 223.116 344 177c0-92.232-74.768-167-167-167S10 84.768 10 177c0 46.116 18.693 87.867 48.914 118.088l-7.07 7.07C19.811 270.129 0 225.879 0 177 0 79.246 79.246 0 177 0z" fill="#E7E8FC" fill-rule="evenodd"/></svg>
```

**Comment by qianshancun** [comment]
`<svg width="354" height="354" xmlns="http://www.w3.org/2000/svg"><path d="M177 0c97.754 0 177 79.246 177 177 0 48.877-19.811 93.127-51.842 125.158l-7.071-7.071C325.307 264.866 344 223.116 344 177c0-92.232-74.768-167-167-167S10 84.768 10 177c0 46.116 18.693 87.867 48.914 118.088l-7.07 7.07C19.811 270.129 0 225.879 0 177 0 79.246 79.246 0 177 0z" fill="#E7E8FC" fill-rule="evenodd"/></svg>`

上传可能有点问题，麻烦用这一段。

**Comment by qianshancun** [comment]
`<svg width="354" height="354" xmlns="http://www.w3.org/2000/svg"><path d="M177 0c97.754 0 177 79.246 177 177 0 48.877-19.811 93.127-51.842 125.158l-7.071-7.071C325.307 264.866 344 223.116 344 177c0-92.232-74.768-167-167-167S10 84.768 10 177c0 46.116 18.693 87.867 48.914 118.088l-7.07 7.07C19.811 270.129 0 225.879 0 177 0 79.246 79.246 0 177 0z" fill="#E7E8FC" fill-rule="evenodd"/></svg>`

上传可能有点问题，麻烦用这一段。

**Comment by meathill** [comment]
不是，实际上我并没有用到这个图片，我需要把这个东西放到 clock-bg 里。

**Comment by qianshancun** [comment]
[newbg-merged.svg.zip](https://github.com/meathill/fasttest/files/6641546/newbg-merged.svg.zip)
看看这样是否可以？ @meathill

**Comment by meathill** [comment]
updated.
