### ISSUE TITLE
无法连接时的UI状态设计

### ISSUE THREAD

**Issue by qianshancun** [meathill/fasttest#6]
当某个资源用户无法连接时，UI上应该有一个提示。

早期先采用一种简单的办法吧，把opacity调低一点：

![image](https://user-images.githubusercontent.com/85496448/121335844-88d11280-c94d-11eb-9677-d970e93302b1.png)

如果某个资源能连上，哪怕速度非常慢，请给至少半颗星。

**Comment by meathill** [comment]
给我个 sketch 吧，或者在原有的 sketch 上调整一下

**Comment by qianshancun** [comment]
> 给我个 sketch 吧，或者在原有的 sketch 上调整一下

抱歉，我没考虑周到。不是”半颗星“，而是一颗星，因为目前只有最少一颗星的素材。

关于opacity，就让这个模块的opacity设置为 `0.5` 即可，如下图所示：

![image](https://user-images.githubusercontent.com/85496448/121690992-169d3100-caf9-11eb-9036-3093030a19b3.png)

以上你看看是否能理解 @meathill

**Comment by meathill** [comment]
fixed in 6452e15。不过我觉得还是要改算法。
