### ISSUE TITLE
样式问题，底部的版权信息margin-top设置一个值

### ISSUE THREAD

**Issue by qianshancun** [meathill/fasttest#9]
这里，请设置一个margin-top，我觉得大一点比较合适，可以设 `160px`

```
#footer {
    margin-top: 160px;
}
```

![image](https://user-images.githubusercontent.com/85496448/121772291-178c9c00-cba7-11eb-92ad-dc3d737a6351.png)

**Comment by meathill** [comment]
移动设备的屏幕默认撑满的话，目前 `margin-top: auto` 应该更好一些，我改成 `padding-top: 10px`（至少保留 10px）了，你可以看下效果。

**Comment by qianshancun** [comment]
> 移动设备的屏幕默认撑满的话，目前 `margin-top: auto` 应该更好一些，我改成 `padding-top: 10px`（至少保留 10px）了，你可以看下效果。

目前可以。
